### ISSUE TITLE
How to auto trigger anomaly chart at specified interval

### ISSUE THREAD

**Issue by arvind008** [awsdocs/amazon-quicksight-user-guide#16]
Currently if we refresh the dataset using scheduled or manual refresh, all the visuals get refreshed automatically. Is their a way or option to configure auto trigger "run row" and "update" the anomaly dashboard.

**Comment by amazoncathan** [comment]
You can schedule anomaly updates for published dashboards. The settings are in the insight's menu in **Configure anomaly**.
