### ISSUE TITLE
super user access (row level security) is incorrect

### ISSUE THREAD

**Issue by kjpgit** [awsdocs/amazon-quicksight-user-guide#21]
"There are two ways to create a superuser. If you use your permissions data set to grant access, list all possible values for each field for that user. Or if you use your permissions data set to deny access, leave the values blank for all restricted fields for that user. In either case, a user configured this way can see all values."

This seems flat out **wrong**.  All the other text says if you are granting access, null means superuser/all access.  And if denying access, you just wouldn't list a user, if you wanted them to have all access.

**Comment by sachinbabuputhur** [comment]
To specify multiple filter values for a single user/group you have to separate the values with a "," with no spaces in between:
'Enterprise, SMB, Startup'   : Wrong
'Enterprise,SMB,Startup'     : Right

Also to allow a user to see the whole dataset you just leave the filter value as blank: ''

**Comment by amazoncathan** [comment]
Content corrected. Thanks!
