### ISSUE TITLE
Help Wanted!

### ISSUE THREAD

**Issue by amazoncathan** [awsdocs/amazon-quicksight-user-guide#4]
If you have ideas for our Amazon QuickSight User Guide, please let me know! Tell me about troubleshooting tips and tricks, examples, tutorials, or content you want to see more (or less) of. 

You can submit a pull request as explained in [these directions](https://github.com/awsdocs/amazon-quicksight-user-guide/blob/master/CONTRIBUTING.md). You can also use the feedback button on any page in the [Amazon QuickSight online documentation](https://docs.aws.amazon.com/en_us/quicksight/latest/user/WhatsNew.html) to send an issue directly to my inbox.

I look forward to hearing from you!

**Comment by ndsang1501** [comment]
I have a pie chart. I add url action for it. With format: 
https://ap-southeast-1.quicksight.aws.amazon.com/*****#p.CategoryName=<<categoryname ....
I have a categoryname that's "F&B". In the normal case, 
it is "https://ap-southeast-1.quicksight.aws.amazon.com/****#p.CategoryName=F%26B". The character **&** will encode to **%26**. However, the character "&" isn't changed. Please help me!
